version: '3.8'
services:
  iris:
    container_name: openflights-iris
    init: true
    command: --check-caps false
    build: .
    image: andreasschneiderixdbde/openflights-iris
    restart: always
    ports: 
    - "127.0.0.1:1972:1972"
    - "127.0.0.1:52773:52773"
    - "127.0.0.1:53773:53773"      
    volumes:
    - ./:/opt/irisbuild
    - ./doc/dbdoc:/opt/irisapp/csp    