version: '3.8'
services:
  iris:
    container_name: iris-openflights
    init: true
    build: .
    restart: always
    ports: 
      - "1972:1972"
      - "52773:52773"
      - "53773:53773"      
    volumes:
      - ./:/opt/irisbuild
      - ./doc/dbdoc:/opt/irisapp/csp